### ISSUE TITLE
Overclocking script fails to execute

### ISSUE THREAD

**Issue by ghost** [adetokunbo/automine#88]
Returns this:
``
yinka@emiakRig:~/bin/automine$ sudo nvidia/overclock.py
[sudo] password for yinka:
ERROR:overclock:could not perform overclock
Traceback (most recent call last):
  File "nvidia/overclock.py", line 127, in main
    _configure_logger()
  File "nvidia/overclock.py", line 119, in _configure_logger
    raise err
KeyError: 'AUTOMINE_LOG_DIR'
yinka@emiakRig:~/bin/automine$
``

**Comment by adetokunbo** [comment]
If you sync to #87, the instructions for performing the overclock are simplified in a way that resolves this.

```bash
automine remote_run apply_overclocks
```

Please try out, and comment/approve

**Comment by adetokunbo** [comment]
@yinkae, can you confirm that this is resolved after #87?  If it is close this bug.

**Comment by adetokunbo** [comment]
Closing.  @yinkae please re-open if there is still an issue.
